---
booktitle: Proceedings of The 37th International Conference on Algorithmic Learning
  Theory
shortname: ALT
year: '2026'
volume: '313'
start: &1 2026-02-23
end: 2026-02-26
published: 2026-05-05
conference_number: '37'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: ALT-2026
month: 0
cycles: false
bibtex_editor: Telgarsky, Matus and Ullman, Jonathan
editor:
- given: Matus
  family: Telgarsky
- given: Jonathan
  family: Ullman
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 37th International Conference on Algorithmic Learning Theory
    Held in Fields Institute, Toronto, Canada on 23-26 February 2026

  Published as Volume 313 by the Proceedings of Machine Learning Research on 05 May 2026.

  Volume Edited by:
    Matus Telgarsky
    Jonathan Ullman

  Series Editors:
    Neil D. Lawrence
date_str: 23--26 Feb
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v313"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v313
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v313
email: ''
conference:
  name: Algorithmic Learning Theory
  url: http://algorithmiclearningtheory.org/alt2026/
  location: Fields Institute, Toronto, Canada
  dates:
  - *1
  - 2026-02-24
  - 2026-02-25
  - 2026-02-26
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: alt26_clean.bib
# Site settings
# Original source:  alt26_clean.bib
